# Generated by Django 5.1.1 on 2024-10-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_editora_genero_livro_editora_livro_genero'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
    ]
