# Generated by Django 5.1.1 on 2024-10-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_editora_table_alter_genero_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='LivroTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.livro')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tag')),
            ],
            options={
                'db_table': 'livro_tag',
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalogo.tag'),
        ),
    ]
