# Generated by Django 5.1.1 on 2024-10-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_tag_livrotag_livro_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='tags',
        ),
        migrations.DeleteModel(
            name='LivroTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
