# Generated by Django 5.1.1 on 2024-10-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_livro_tags_delete_livrotag_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalogo.tag'),
        ),
    ]
