# Generated by Django 5.1 on 2024-10-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_tag_livro_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='editora',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='genero',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='livro',
            name='numero_paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
