# Generated by Django 5.1 on 2024-10-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_autor_data_nascimento_autor_nacionalidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='email',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='numero_paginas',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='descricao',
        ),
    ]
