# Generated by Django 5.1.1 on 2024-10-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_livroview_alter_autor_table_alter_editora_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorView',
            fields=[
                ('autor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('autor_nome', models.CharField(max_length=100)),
                ('autor_biografia', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'autores_view',
                'managed': False,
            },
        ),
    ]
