# Generated by Django 5.1.1 on 2024-11-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
