# Generated by Django 5.1.3 on 2024-11-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoUsuarioView',
            fields=[
                ('usuario', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('livro', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Empréstimo por Usuário',
                'verbose_name_plural': 'Empréstimos por Usuário',
                'db_table': 'emprestimos_usuario',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
    ]
