# Generated by Django 5.1.3 on 2024-11-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
